package teams

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"

	"golang.org/x/net/html"
)

// teamsCardsToMarkdown turns the card payload carried in message properties
// into the small Markdown subset rendered by Loom. Teams serializes this field
// inconsistently: cards, their content, or both can be JSON strings.
func teamsCardsToMarkdown(properties map[string]any) string {
	var raw any
	for key, value := range properties {
		if strings.EqualFold(key, "cards") {
			raw = value
			break
		}
	}
	if raw == nil {
		return ""
	}
	lines := renderTeamsCardValue(decodeTeamsCardJSON(raw))
	return uniqueTeamsCardLines(lines)
}

// teamsSwiftCardsToMarkdown handles RichText/Media_Card messages generated by
// Teams bots and Workflows. Their Adaptive Card isn't in properties.cards: it
// is embedded as a base64-encoded Bot Framework activity in <swift b64="…">.
func teamsSwiftCardsToMarkdown(content string) string {
	payloads := teamsSwiftCardPayloads(content)
	var lines []string
	for _, payload := range payloads {
		var card any
		if json.Unmarshal([]byte(payload), &card) == nil {
			lines = append(lines, renderTeamsCardValue(card)...)
		}
	}
	return uniqueTeamsCardLines(lines)
}

func teamsSwiftCardPayloads(content string) []string {
	root, err := html.Parse(strings.NewReader(content))
	if err != nil {
		return nil
	}
	var payloads []string
	var walk func(*html.Node)
	walk = func(node *html.Node) {
		if node.Type == html.ElementNode && strings.EqualFold(node.Data, "swift") {
			for _, attribute := range node.Attr {
				if !strings.EqualFold(attribute.Key, "b64") {
					continue
				}
				decoded, decodeErr := base64.StdEncoding.DecodeString(strings.TrimSpace(attribute.Val))
				if decodeErr != nil {
					continue
				}
				var activity map[string]any
				if json.Unmarshal(decoded, &activity) != nil {
					continue
				}
				attachments, _ := activity["attachments"].([]any)
				for _, rawAttachment := range attachments {
					attachment, _ := rawAttachment.(map[string]any)
					contentType, _ := attachment["contentType"].(string)
					if !strings.Contains(strings.ToLower(contentType), "adaptive") {
						continue
					}
					if encoded, marshalErr := json.Marshal(attachment["content"]); marshalErr == nil {
						payloads = append(payloads, string(encoded))
					}
				}
			}
		}
		for child := node.FirstChild; child != nil; child = child.NextSibling {
			walk(child)
		}
	}
	walk(root)
	return payloads
}

func uniqueTeamsCardLines(lines []string) string {
	seen := make(map[string]struct{}, len(lines))
	out := lines[:0]
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if _, exists := seen[line]; exists {
			continue
		}
		seen[line] = struct{}{}
		out = append(out, line)
	}
	return strings.Join(out, "\n\n")
}

func decodeTeamsCardJSON(value any) any {
	text, ok := value.(string)
	if !ok {
		return value
	}
	text = strings.TrimSpace(text)
	if text == "" || text == "null" {
		return nil
	}
	var decoded any
	if json.Unmarshal([]byte(text), &decoded) == nil {
		return decodeTeamsCardJSON(decoded)
	}
	return text
}

func renderTeamsCardValue(value any) []string {
	value = decodeTeamsCardJSON(value)
	switch card := value.(type) {
	case []any:
		var out []string
		for _, item := range card {
			out = append(out, renderTeamsCardValue(item)...)
		}
		return out
	case map[string]any:
		return renderTeamsCardObject(card)
	case string:
		if looksLikeTeamsHTML(card) {
			return []string{teamsHTMLToMarkdown(card)}
		}
		return []string{card}
	default:
		return nil
	}
}

func renderTeamsCardObject(card map[string]any) []string {
	typeName := strings.ToLower(cardString(card, "type"))
	if strings.Contains(typeName, "openurl") {
		return renderTeamsCardAction(card)
	}
	if strings.Contains(typeName, "submit") || strings.Contains(typeName, "showcard") {
		if title := cardString(card, "title"); title != "" {
			return []string{title}
		}
	}
	if strings.Contains(typeName, "textblock") {
		return renderTeamsCardValue(card["text"])
	}
	if strings.Contains(typeName, "factset") {
		return renderTeamsCardFacts(card["facts"])
	}
	if strings.Contains(typeName, "image") {
		alt, imageURL := cardString(card, "altText"), cardString(card, "url")
		if alt != "" && imageURL != "" {
			return []string{fmt.Sprintf("[%s](%s)", alt, imageURL)}
		}
		return renderTeamsCardValue(alt)
	}

	var out []string
	// Title-like fields belong before the structural children on Hero,
	// Thumbnail, connector and Adaptive Card variants.
	for _, key := range []string{"title", "subtitle", "text"} {
		out = append(out, renderTeamsCardValue(card[key])...)
	}
	for _, key := range []string{"body", "facts", "items", "columns", "actions", "buttons", "sections", "content", "attachments"} {
		if key == "facts" {
			out = append(out, renderTeamsCardFacts(card[key])...)
		} else {
			out = append(out, renderTeamsCardValue(card[key])...)
		}
	}
	return out
}

func renderTeamsCardFacts(value any) []string {
	items, ok := decodeTeamsCardJSON(value).([]any)
	if !ok {
		return renderTeamsCardValue(value)
	}
	out := make([]string, 0, len(items))
	for _, item := range items {
		fact, ok := item.(map[string]any)
		if !ok {
			continue
		}
		title, value := cardString(fact, "title"), cardString(fact, "value")
		switch {
		case title != "" && value != "":
			out = append(out, "**"+strings.TrimSuffix(title, ":")+":** "+value)
		case value != "":
			out = append(out, value)
		case title != "":
			out = append(out, title)
		}
	}
	return out
}

func renderTeamsCardAction(card map[string]any) []string {
	title, target := cardString(card, "title"), cardString(card, "url")
	if target == "" {
		target = cardString(card, "value")
	}
	if title != "" && target != "" {
		return []string{fmt.Sprintf("[%s](%s)", title, target)}
	}
	return renderTeamsCardValue(firstNonNil(title, target))
}

func cardString(card map[string]any, wanted string) string {
	for key, value := range card {
		if strings.EqualFold(key, wanted) {
			if text, ok := decodeTeamsCardJSON(value).(string); ok {
				return strings.TrimSpace(text)
			}
		}
	}
	return ""
}

func firstNonNil(values ...string) any {
	for _, value := range values {
		if value != "" {
			return value
		}
	}
	return nil
}

func isTeamsUnsupportedCardPlaceholder(body string) bool {
	lower := strings.ToLower(body)
	return strings.Contains(lower, "go.skype.com/cards.unsupported") ||
		(strings.TrimSpace(lower) == "card" || strings.TrimSpace(lower) == "card.")
}
