#!/usr/bin/env node

/**
 * Script to generate emojiMap.ts from emojilib's emoji-en-US.json
 * 
 * This script:
 * 1. Downloads emoji-en-US.json from emojilib
 * 2. Inverts the mapping (emoji -> [names] becomes name -> emoji)
 * 3. Generates a TypeScript file with the mapping
 * 
 * Usage: node scripts/generateEmojiMap.js
 */

import { fileURLToPath } from 'url';
import fs from 'fs';
import https from 'https';
import path from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const EMOJILIB_URL = 'https://raw.githubusercontent.com/muan/emojilib/main/dist/emoji-en-US.json';
const OUTPUT_FILE = path.join(__dirname, '../src/lib/emojiMap.ts');

function downloadFile(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode !== 200) {
        reject(new Error(`Failed to download: ${res.statusCode}`));
        return;
      }
      
      let data = '';
      res.on('data', (chunk) => {
        data += chunk;
      });
      
      res.on('end', () => {
        try {
          resolve(JSON.parse(data));
        } catch (err) {
          reject(err);
        }
      });
    }).on('error', reject);
  });
}

function generateEmojiMap(emojilibData) {
  const nameToEmoji = {};
  
  // Iterate through each emoji and its aliases
  for (const [emoji, names] of Object.entries(emojilibData)) {
    if (!Array.isArray(names)) {
      continue;
    }
    
    // Map each name/alias to the emoji
    for (const name of names) {
      // Normalize name: convert to lowercase and replace spaces/underscores
      const normalizedName = name.toLowerCase().replace(/\s+/g, '_');
      
      // Only add if not already mapped (first occurrence wins)
      if (!nameToEmoji[normalizedName]) {
        nameToEmoji[normalizedName] = emoji;
      }
    }
  }
  
  // Add Slack-specific mappings not in emojilib or with different names
  const slackSpecificMappings = {
    'spiral_calendar_pad': '📓',
    'spiral_calendar': '📓',
    'spiral_notepad': '📓',
    'sweat_smile': '😅',
    'white_frowning_face': '☹️',
    'face_with_thermometer': '🤒',
    'slightly_smiling_face': '🙂',
    'upside_down_face': '🙃',
    'face_with_rolling_eyes': '🙄',
    'lying_face': '🤥',
    'drooling_face': '🤤',
    'nauseated_face': '🤢',
    'face_vomiting': '🤮',
    'sneezing_face': '🤧',
    'hot_face': '🥵',
    'cold_face': '🥶',
    'woozy_face': '🥴',
    'exploding_head': '🤯',
    'face_with_cowboy_hat': '🤠',
    'partying_face': '🥳',
    'disguised_face': '🥸',
    'smiling_face_with_sunglasses': '😎',
    'nerd_face': '🤓',
    'face_with_monocle': '🧐',
    'slightly_frowning_face': '🙁',
    'face_with_open_mouth': '😮',
    'pleading_face': '🥺',
    'frowning_face': '😦',
    'cold_sweat': '😰',
    'disappointed_relieved': '😥',
    'yawning_face': '🥱',
  };
  
  // Merge Slack-specific mappings (they override emojilib if there's a conflict)
  Object.assign(nameToEmoji, slackSpecificMappings);
  
  return nameToEmoji;
}

function escapeString(str) {
  // Escape backslashes and quotes in the string
  return str
    .replace(/\\/g, '\\\\')  // Escape backslashes first
    .replace(/"/g, '\\"');   // Escape quotes
}

function generateTypeScriptFile(nameToEmoji) {
  const entries = Object.entries(nameToEmoji)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, emoji]) => {
      // Escape both the name and emoji strings
      const escapedName = escapeString(name);
      const escapedEmoji = escapeString(emoji);
      return `  "${escapedName}": "${escapedEmoji}"`;
    })
    .join(',\n');
  
  return `/**
 * Mapping of Slack emoji names to Unicode emojis
 * Generated from emojilib (https://github.com/muan/emojilib)
 * 
 * This map allows converting Slack emoji names (e.g., ":face_with_thermometer:")
 * to their Unicode equivalents (e.g., "🤒")
 * 
 * Auto-generated by scripts/generateEmojiMap.js
 * Last updated: ${new Date().toISOString()}
 */
export const unicodeEmojiMap: Record<string, string> = {
${entries}
};
`;
}

async function main() {
  console.log('Downloading emoji-en-US.json from emojilib...');
  
  try {
    const emojilibData = await downloadFile(EMOJILIB_URL);
    console.log(`Downloaded ${Object.keys(emojilibData).length} emojis`);
    
    console.log('Generating emoji map...');
    const nameToEmoji = generateEmojiMap(emojilibData);
    console.log(`Generated ${Object.keys(nameToEmoji).length} name mappings`);
    
    console.log('Generating TypeScript file...');
    const tsContent = generateTypeScriptFile(nameToEmoji);
    
    console.log(`Writing to ${OUTPUT_FILE}...`);
    fs.writeFileSync(OUTPUT_FILE, tsContent, 'utf8');
    
    console.log('✅ Successfully generated emojiMap.ts');
  } catch (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  }
}

main();
