// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {core} from '../models';
import {time} from '../models';

export function AddGroupParticipants(arg1:string,arg2:Array<string>):Promise<void>;

export function AddReaction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AutoLoginGoogleChatGaia(arg1:string):Promise<Record<string, string>>;

export function AutoLoginSlack(arg1:string,arg2:string):Promise<void>;

export function AutoLoginTeams(arg1:string,arg2:string):Promise<void>;

export function AutoPairGoogleMessages(arg1:string):Promise<string>;

export function CancelScheduledMessage(arg1:string,arg2:string):Promise<void>;

export function CompleteGoogleMessagesLogin(arg1:string):Promise<void>;

export function ConfigureProvider(arg1:string):Promise<void>;

export function ConnectProvider(arg1:string):Promise<void>;

export function CreateGroup(arg1:string,arg2:Array<string>):Promise<models.Conversation>;

export function CreateProvider(arg1:string,arg2:Record<string, any>,arg3:string,arg4:string):Promise<string>;

export function CreateProviderWithOptions(arg1:string,arg2:Record<string, any>,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function DeleteMessage(arg1:string,arg2:string):Promise<void>;

export function DemoteGroupAdmins(arg1:string,arg2:Array<string>):Promise<void>;

export function DisconnectProvider(arg1:string):Promise<void>;

export function EditMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FetchLinkPreview(arg1:string):Promise<main.LinkPreview>;

export function ForceSyncCompletion(arg1:string):Promise<void>;

export function ForwardAttachment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetAllActiveCalls():Promise<Record<string, boolean>>;

export function GetAllLastMessageTimestamps():Promise<Record<string, number>>;

export function GetAllLastMessages():Promise<Record<string, models.Message>>;

export function GetAllMessageCounts():Promise<Record<string, number>>;

export function GetAttachmentData(arg1:string):Promise<string>;

export function GetAvailableProviders():Promise<Array<core.ProviderInfo>>;

export function GetAvatar(arg1:string):Promise<string>;

export function GetCapabilities(arg1:string):Promise<core.Capabilities>;

export function GetCommunicationStats(arg1:time.Time,arg2:time.Time):Promise<models.CommunicationStats>;

export function GetConfig():Promise<Record<string, any>>;

export function GetConfiguredProviders():Promise<Array<core.ProviderInfo>>;

export function GetContactAliases():Promise<Record<string, string>>;

export function GetContactExchangeStats(arg1:string,arg2:string):Promise<models.ContactExchangeStats>;

export function GetContactProfile(arg1:string,arg2:string):Promise<models.ContactProfile>;

export function GetConversationState(arg1:string):Promise<models.Conversation>;

export function GetConversationsWithMessages():Promise<Array<string>>;

export function GetCustomEmojis(arg1:string):Promise<Record<string, string>>;

export function GetGoogleChatWebCookies(arg1:string):Promise<Record<string, string>>;

export function GetGroupDetails(arg1:string):Promise<models.GroupDetails>;

export function GetGroupParticipants(arg1:string):Promise<Array<models.GroupParticipant>>;

export function GetMessagesForConversation(arg1:string):Promise<Array<models.Message>>;

export function GetMessagesForConversationBefore(arg1:string,arg2:time.Time):Promise<Array<models.Message>>;

export function GetMetaContacts():Promise<Array<models.MetaContact>>;

export function GetParticipantNames(arg1:Array<string>):Promise<Record<string, string>>;

export function GetPinnedMessageContext(arg1:string,arg2:string):Promise<models.MessageContext>;

export function GetPinnedMessages(arg1:string):Promise<Array<models.MessagePin>>;

export function GetProviderContacts(arg1:string):Promise<Array<models.MetaContact>>;

export function GetProviderQRCode(arg1:string):Promise<string>;

export function GetProviderSchema(arg1:string):Promise<Record<string, any>>;

export function GetScheduledMessages(arg1:string):Promise<Array<models.ScheduledMessage>>;

export function GetThreadMessages(arg1:string,arg2:string):Promise<Array<models.Message>>;

export function GetThreadSummaries(arg1:string,arg2:Array<string>):Promise<Array<models.ThreadSummary>>;

export function GetThreads(arg1:string):Promise<Array<models.Message>>;

export function GetUnreadMessageLocations(arg1:string,arg2:Array<string>):Promise<Array<models.UnreadMessageLocation>>;

export function LeaveGroup(arg1:string):Promise<void>;

export function MarkConversationAsRead(arg1:string):Promise<void>;

export function MarkMessageAsPlayed(arg1:string,arg2:string):Promise<void>;

export function MarkMessageAsRead(arg1:string,arg2:string):Promise<void>;

export function OpenConversation(arg1:models.OpenConversationRequest):Promise<models.ConversationResolution>;

export function OpenFile(arg1:string):Promise<void>;

export function PinMessage(arg1:string,arg2:string):Promise<models.MessagePin>;

export function PromoteGroupAdmins(arg1:string,arg2:Array<string>):Promise<void>;

export function RemoveGroupParticipants(arg1:string,arg2:Array<string>):Promise<void>;

export function RemoveProvider(arg1:string):Promise<void>;

export function RemoveReaction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetProviderAuthentication(arg1:string):Promise<void>;

export function SaveAttachmentToFile(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:Record<string, any>):Promise<void>;

export function ScheduleMessage(arg1:string,arg2:string,arg3:time.Time,arg4:string):Promise<models.ScheduledMessage>;

export function SearchMessages(arg1:string,arg2:number):Promise<models.MessageSearchPage>;

export function SearchProviderContacts(arg1:string,arg2:string):Promise<Array<models.MetaContact>>;

export function SendFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<models.Message>;

export function SendReply(arg1:string,arg2:string,arg3:string):Promise<models.Message>;

export function SendThreadFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.Message>;

export function SendThreadFileFromPath(arg1:string,arg2:string,arg3:string):Promise<models.Message>;

export function SendThreadMessage(arg1:string,arg2:string,arg3:string):Promise<models.Message>;

export function SendThreadReply(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Message>;

export function SendTypingIndicator(arg1:string,arg2:boolean):Promise<void>;

export function SetActiveProvider(arg1:string):Promise<void>;

export function SetContactAlias(arg1:string,arg2:string):Promise<void>;

export function SetContactAliasForConversation(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetConversationMuted(arg1:string,arg2:boolean):Promise<void>;

export function StartGoogleMessagesLogin(arg1:string,arg2:string):Promise<string>;

export function SyncAllProviders():Promise<void>;

export function SyncProvider(arg1:string):Promise<void>;

export function UnpinMessage(arg1:string,arg2:string):Promise<void>;

export function UpdateGroupDescription(arg1:string,arg2:string):Promise<void>;

export function UpdateGroupName(arg1:string,arg2:string):Promise<void>;

export function UpdateGroupPhoto(arg1:string,arg2:string):Promise<void>;

export function UpdateSystemTrayBadge(arg1:number):Promise<void>;
