// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddReaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddReaction'](arg1, arg2, arg3);
}

export function ConfigureProvider(arg1) {
  return window['go']['main']['App']['ConfigureProvider'](arg1);
}

export function ConnectProvider(arg1) {
  return window['go']['main']['App']['ConnectProvider'](arg1);
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function CreateProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProvider'](arg1, arg2, arg3, arg4);
}

export function CreateProviderWithOptions(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateProviderWithOptions'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteMessage(arg1, arg2) {
  return window['go']['main']['App']['DeleteMessage'](arg1, arg2);
}

export function DisconnectProvider(arg1) {
  return window['go']['main']['App']['DisconnectProvider'](arg1);
}

export function EditMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditMessage'](arg1, arg2, arg3);
}

export function FetchLinkPreview(arg1) {
  return window['go']['main']['App']['FetchLinkPreview'](arg1);
}

export function ForceSyncCompletion(arg1) {
  return window['go']['main']['App']['ForceSyncCompletion'](arg1);
}

export function GetAllActiveCalls() {
  return window['go']['main']['App']['GetAllActiveCalls']();
}

export function GetAllLastMessageTimestamps() {
  return window['go']['main']['App']['GetAllLastMessageTimestamps']();
}

export function GetAllLastMessages() {
  return window['go']['main']['App']['GetAllLastMessages']();
}

export function GetAllMessageCounts() {
  return window['go']['main']['App']['GetAllMessageCounts']();
}

export function GetAttachmentData(arg1) {
  return window['go']['main']['App']['GetAttachmentData'](arg1);
}

export function GetAvailableProviders() {
  return window['go']['main']['App']['GetAvailableProviders']();
}

export function GetAvatar(arg1) {
  return window['go']['main']['App']['GetAvatar'](arg1);
}

export function GetCapabilities(arg1) {
  return window['go']['main']['App']['GetCapabilities'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfiguredProviders() {
  return window['go']['main']['App']['GetConfiguredProviders']();
}

export function GetContactAliases() {
  return window['go']['main']['App']['GetContactAliases']();
}

export function GetConversationsWithMessages() {
  return window['go']['main']['App']['GetConversationsWithMessages']();
}

export function GetCustomEmojis(arg1) {
  return window['go']['main']['App']['GetCustomEmojis'](arg1);
}

export function GetGroupParticipants(arg1) {
  return window['go']['main']['App']['GetGroupParticipants'](arg1);
}

export function GetMessagesForConversation(arg1) {
  return window['go']['main']['App']['GetMessagesForConversation'](arg1);
}

export function GetMessagesForConversationBefore(arg1, arg2) {
  return window['go']['main']['App']['GetMessagesForConversationBefore'](arg1, arg2);
}

export function GetMetaContacts() {
  return window['go']['main']['App']['GetMetaContacts']();
}

export function GetParticipantNames(arg1) {
  return window['go']['main']['App']['GetParticipantNames'](arg1);
}

export function GetProviderQRCode(arg1) {
  return window['go']['main']['App']['GetProviderQRCode'](arg1);
}

export function GetProviderSchema(arg1) {
  return window['go']['main']['App']['GetProviderSchema'](arg1);
}

export function GetThreadMessages(arg1, arg2) {
  return window['go']['main']['App']['GetThreadMessages'](arg1, arg2);
}

export function GetThreads(arg1) {
  return window['go']['main']['App']['GetThreads'](arg1);
}

export function MarkConversationAsRead(arg1) {
  return window['go']['main']['App']['MarkConversationAsRead'](arg1);
}

export function MarkMessageAsPlayed(arg1, arg2) {
  return window['go']['main']['App']['MarkMessageAsPlayed'](arg1, arg2);
}

export function MarkMessageAsRead(arg1, arg2) {
  return window['go']['main']['App']['MarkMessageAsRead'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function RemoveProvider(arg1) {
  return window['go']['main']['App']['RemoveProvider'](arg1);
}

export function RemoveReaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveReaction'](arg1, arg2, arg3);
}

export function SaveAttachmentToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveAttachmentToFile'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendFile'](arg1, arg2, arg3, arg4);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendReply(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendReply'](arg1, arg2, arg3);
}

export function SendThreadMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendThreadMessage'](arg1, arg2, arg3);
}

export function SetActiveProvider(arg1) {
  return window['go']['main']['App']['SetActiveProvider'](arg1);
}

export function SetContactAlias(arg1, arg2) {
  return window['go']['main']['App']['SetContactAlias'](arg1, arg2);
}

export function SyncProvider(arg1) {
  return window['go']['main']['App']['SyncProvider'](arg1);
}

export function UpdateSystemTrayBadge(arg1) {
  return window['go']['main']['App']['UpdateSystemTrayBadge'](arg1);
}
