// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddReaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddReaction'](arg1, arg2, arg3);
}

export function ConnectProvider(arg1) {
  return window['go']['main']['App']['ConnectProvider'](arg1);
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function CreateProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProvider'](arg1, arg2, arg3, arg4);
}

export function DeleteMessage(arg1, arg2) {
  return window['go']['main']['App']['DeleteMessage'](arg1, arg2);
}

export function EditMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditMessage'](arg1, arg2, arg3);
}

export function ForceSyncCompletion() {
  return window['go']['main']['App']['ForceSyncCompletion']();
}

export function GetAttachmentData(arg1) {
  return window['go']['main']['App']['GetAttachmentData'](arg1);
}

export function GetAvailableProviders() {
  return window['go']['main']['App']['GetAvailableProviders']();
}

export function GetAvatar(arg1) {
  return window['go']['main']['App']['GetAvatar'](arg1);
}

export function GetClipboardFile() {
  return window['go']['main']['App']['GetClipboardFile']();
}

export function GetConfiguredProviders() {
  return window['go']['main']['App']['GetConfiguredProviders']();
}

export function GetContactAliases() {
  return window['go']['main']['App']['GetContactAliases']();
}

export function GetGroupParticipants(arg1) {
  return window['go']['main']['App']['GetGroupParticipants'](arg1);
}

export function GetMessagesForConversation(arg1) {
  return window['go']['main']['App']['GetMessagesForConversation'](arg1);
}

export function GetMessagesForConversationBefore(arg1, arg2) {
  return window['go']['main']['App']['GetMessagesForConversationBefore'](arg1, arg2);
}

export function GetMetaContacts() {
  return window['go']['main']['App']['GetMetaContacts']();
}

export function GetParticipantNames(arg1) {
  return window['go']['main']['App']['GetParticipantNames'](arg1);
}

export function GetProviderQRCode(arg1) {
  return window['go']['main']['App']['GetProviderQRCode'](arg1);
}

export function GetThreads(arg1) {
  return window['go']['main']['App']['GetThreads'](arg1);
}

export function MarkMessageAsPlayed(arg1, arg2) {
  return window['go']['main']['App']['MarkMessageAsPlayed'](arg1, arg2);
}

export function MarkMessageAsRead(arg1, arg2) {
  return window['go']['main']['App']['MarkMessageAsRead'](arg1, arg2);
}

export function RemoveProvider(arg1) {
  return window['go']['main']['App']['RemoveProvider'](arg1);
}

export function RemoveReaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveReaction'](arg1, arg2, arg3);
}

export function ResolveLID(arg1) {
  return window['go']['main']['App']['ResolveLID'](arg1);
}

export function SendFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendFile'](arg1, arg2, arg3, arg4);
}

export function SendFileFromPath(arg1, arg2) {
  return window['go']['main']['App']['SendFileFromPath'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendReply(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendReply'](arg1, arg2, arg3);
}

export function SetContactAlias(arg1, arg2) {
  return window['go']['main']['App']['SetContactAlias'](arg1, arg2);
}

export function SyncProvider(arg1) {
  return window['go']['main']['App']['SyncProvider'](arg1);
}

export function UpdateSystemTrayBadge(arg1) {
  return window['go']['main']['App']['UpdateSystemTrayBadge'](arg1);
}
