// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {core} from '../models';
import {main} from '../models';
import {time} from '../models';

export function AddReaction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConnectProvider(arg1:string):Promise<void>;

export function CreateGroup(arg1:string,arg2:Array<string>):Promise<models.Conversation>;

export function CreateProvider(arg1:string,arg2:core.ProviderConfig,arg3:string,arg4:string):Promise<string>;

export function DeleteMessage(arg1:string,arg2:string):Promise<void>;

export function EditMessage(arg1:string,arg2:string,arg3:string):Promise<models.Message>;

export function ForceSyncCompletion():Promise<void>;

export function GetAttachmentData(arg1:string):Promise<string>;

export function GetAvailableProviders():Promise<Array<core.ProviderInfo>>;

export function GetAvatar(arg1:string):Promise<string>;

export function GetClipboardFile():Promise<main.ClipboardFile>;

export function GetConfiguredProviders():Promise<Array<core.ProviderInfo>>;

export function GetContactAliases():Promise<Record<string, string>>;

export function GetGroupParticipants(arg1:string):Promise<Array<models.GroupParticipant>>;

export function GetMessagesForConversation(arg1:string):Promise<Array<models.Message>>;

export function GetMessagesForConversationBefore(arg1:string,arg2:time.Time):Promise<Array<models.Message>>;

export function GetMetaContacts():Promise<Array<models.MetaContact>>;

export function GetParticipantNames(arg1:Array<string>):Promise<Record<string, string>>;

export function GetProviderQRCode(arg1:string):Promise<string>;

export function GetThreads(arg1:string):Promise<Array<models.Message>>;

export function MarkMessageAsPlayed(arg1:string,arg2:string):Promise<void>;

export function MarkMessageAsRead(arg1:string,arg2:string):Promise<void>;

export function RemoveProvider(arg1:string):Promise<void>;

export function RemoveReaction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResolveLID(arg1:string):Promise<string>;

export function SendFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Message>;

export function SendFileFromPath(arg1:string,arg2:string):Promise<models.Message>;

export function SendMessage(arg1:string,arg2:string):Promise<models.Message>;

export function SendReply(arg1:string,arg2:string,arg3:string):Promise<models.Message>;

export function SetContactAlias(arg1:string,arg2:string):Promise<void>;

export function SyncProvider(arg1:string):Promise<void>;

export function UpdateSystemTrayBadge(arg1:number):Promise<void>;
